import './bootstrap';

const TOKEN = 'netio_command_token';
const root = document.querySelector('#app');
const state = { screen: 'overview', summary: {}, devices: [], logs: [], user: null };
const esc = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[c]);
const number = (value) => new Intl.NumberFormat('id-ID').format(value || 0);
const date = (value) => value ? new Date(value).toLocaleString('id-ID', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) : 'Belum ada data';
const bps = (value) => { const n = Number(value || 0); if (n >= 1e9) return `${(n / 1e9).toFixed(1)} Gbps`; if (n >= 1e6) return `${(n / 1e6).toFixed(1)} Mbps`; if (n >= 1e3) return `${(n / 1e3).toFixed(1)} Kbps`; return `${Math.round(n)} bps`; };
const svg = (name) => ({
    grid: '<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>',
    router: '<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 9h.01M11 9h.01M15 9h.01M7 15h10"/></svg>',
    activity: '<svg viewBox="0 0 24 24"><path d="M3 12h4l2-7 4 14 2-7h6"/></svg>',
    terminal: '<svg viewBox="0 0 24 24"><path d="m5 7 5 5-5 5M13 17h6"/></svg>',
    settings: '<svg viewBox="0 0 24 24"><path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM4 12H2m20 0h-2M12 2v2m0 16v2"/></svg>',
    logout: '<svg viewBox="0 0 24 24"><path d="M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-5"/></svg>',
    plus: '<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
    search: '<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>',
    refresh: '<svg viewBox="0 0 24 24"><path d="M20 11a8.1 8.1 0 0 0-14.8-3L3 11m0 0V5m0 6h6M4 13a8.1 8.1 0 0 0 14.8 3L21 13m0 0v6m0-6h-6"/></svg>',
    arrow: '<svg viewBox="0 0 24 24"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>',
})[name] || '';
const api = async (path, options = {}) => { const response = await fetch(`/api/v1${path}`, { ...options, headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...(localStorage.getItem(TOKEN) ? { Authorization: `Bearer ${localStorage.getItem(TOKEN)}` } : {}), ...(options.headers || {}) } }); const body = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.message || 'Request gagal diproses.'); return body; };
const toast = (message, type = 'success') => { const el = document.createElement('div'); el.className = `toast toast-${type}`; el.textContent = message; document.body.append(el); setTimeout(() => el.remove(), 3500); };
const status = (value) => `<span class="status status-${value === 'online' ? 'online' : 'offline'}"><i></i>${value === 'online' ? 'Online' : 'Offline'}</span>`;

function renderLogin() {
    root.innerHTML = `<main class="login-page"><section class="login-art"><div class="brand-mark">N<span>•</span></div><p class="eyebrow">NETWORK OPERATIONS CENTER</p><h1>See the network<br><em>clearly.</em></h1><p class="login-lede">Satu ruang kendali untuk menjaga konektivitas, kesehatan perangkat, dan layanan pelanggan tetap online.</p><div class="signal-card"><span class="signal-dot"></span><div><strong>Network intelligence</strong><small>Monitoring layer is ready</small></div><b>24/7</b></div></section><section class="login-panel"><div class="login-box"><p class="eyebrow">WELCOME BACK</p><h2>Masuk ke Command Center</h2><p class="muted">Gunakan akun NOC kamu untuk melanjutkan.</p><form id="login-form"><label>Email<input name="email" type="email" placeholder="admin@netio.local" value="admin@netio.local" required></label><label>Password<input name="password" type="password" placeholder="••••••••" value="password" required></label><button class="primary-button full" type="submit">Masuk ke dashboard ${svg('arrow')}</button><p class="form-error" id="login-error"></p></form><p class="login-hint">Development account: <code>admin@netio.local</code> / <code>password</code></p></div><span class="login-footer">NETIO COMMAND <span>·</span> v1.0.0</span></section></main>`;
    document.querySelector('#login-form').onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const button = event.currentTarget.querySelector('button'); button.disabled = true; button.textContent = 'Memproses...'; try { const result = await api('/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); localStorage.setItem(TOKEN, result.data.token); state.user = result.data.user; renderApp(); await loadData(); } catch (error) { document.querySelector('#login-error').textContent = error.message; button.disabled = false; button.innerHTML = `Masuk ke dashboard ${svg('arrow')}`; } };
}

function renderApp() {
    const name = state.user?.name || 'NOC Administrator';
    root.innerHTML = `<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="sidebar-brand"><div class="brand-mark">N<span>•</span></div><div><strong>netio</strong><small>command center</small></div></div><div class="workspace-label">WORKSPACE</div><nav><button class="nav-item ${state.screen === 'overview' ? 'active' : ''}" data-screen="overview">${svg('grid')}<span>Overview</span></button><button class="nav-item ${state.screen === 'devices' ? 'active' : ''}" data-screen="devices">${svg('router')}<span>Network devices</span><b class="nav-count">${state.devices.length || ''}</b></button><button class="nav-item ${state.screen === 'syslog' ? 'active' : ''}" data-screen="syslog">${svg('activity')}<span>Syslog events</span></button><button class="nav-item disabled">${svg('terminal')}<span>Remote CLI</span><small>SOON</small></button></nav><div class="sidebar-bottom"><button class="nav-item disabled">${svg('settings')}<span>Settings</span></button><button class="user-menu" id="logout-button"><span class="avatar">${esc(name.charAt(0))}</span><span><strong>${esc(name)}</strong><small>Administrator</small></span>${svg('logout')}</button></div></aside><main class="main-content"><header class="topbar"><button class="mobile-menu" id="mobile-menu">☰</button><div><span class="breadcrumb">NETIO COMMAND <b>/</b> ${state.screen === 'overview' ? 'OVERVIEW' : state.screen === 'devices' ? 'NETWORK DEVICES' : 'SYSLOG EVENTS'}</span><h1>${state.screen === 'overview' ? 'Good morning, NOC.' : state.screen === 'devices' ? 'Network devices' : 'Syslog events'}</h1></div><div class="topbar-actions"><span class="live-indicator"><i></i>Live polling</span><button class="icon-button" id="refresh-button">${svg('refresh')}</button><span class="top-avatar">${esc(name.charAt(0))}</span></div></header><div id="screen-content" class="screen-content"></div></main></div>`;
    document.querySelectorAll('[data-screen]').forEach((button) => button.onclick = () => { state.screen = button.dataset.screen; renderApp(); });
    document.querySelector('#logout-button').onclick = async () => { try { await api('/auth/logout', { method: 'POST' }); } catch {} localStorage.removeItem(TOKEN); renderLogin(); };
    document.querySelector('#refresh-button').onclick = async () => { await loadData(); toast('Data berhasil diperbarui.'); };
    document.querySelector('#mobile-menu').onclick = () => document.querySelector('#sidebar').classList.toggle('open');
    renderScreen();
}

function renderOverview() {
    const s = state.summary;
    document.querySelector('#screen-content').innerHTML = `<section class="welcome-strip"><div><span class="eyebrow">THURSDAY, 10 SEPTEMBER 2026</span><h2>Network at a glance</h2><p class="muted">Pantau kesehatan infrastruktur dan respons insiden dari satu tempat.</p></div><button class="outline-button" id="overview-refresh">${svg('refresh')} Refresh data</button></section><section class="metric-grid"><article class="metric-card accent-teal"><div class="metric-top"><span>Devices online</span><span class="metric-icon">${svg('router')}</span></div><strong>${number(s.devices_online)}</strong><small><i></i>${number(s.devices_offline)} devices offline</small></article><article class="metric-card accent-blue"><div class="metric-top"><span>Active ONUs</span><span class="metric-icon">${svg('activity')}</span></div><strong>${number(s.onus_online)}</strong><small>${number(s.onus_los)} with LOS signal</small></article><article class="metric-card accent-orange"><div class="metric-top"><span>Aggregate traffic</span><span class="metric-icon">${svg('arrow')}</span></div><strong>${bps((s.aggregate_rx_bps || 0) + (s.aggregate_tx_bps || 0))}</strong><small>RX ${bps(s.aggregate_rx_bps)} <span class="divider">·</span> TX ${bps(s.aggregate_tx_bps)}</small></article><article class="metric-card accent-purple"><div class="metric-top"><span>Power off</span><span class="metric-icon">${svg('activity')}</span></div><strong>${number(s.onus_power_off)}</strong><small>ONU membutuhkan perhatian</small></article></section><section class="dashboard-grid"><article class="content-card"><div class="card-header"><div><span class="eyebrow">INFRASTRUCTURE</span><h3>Device health</h3></div><button class="text-button" data-screen="devices">View all ${svg('arrow')}</button></div><div class="device-list">${state.devices.length ? state.devices.slice(0, 5).map((d) => `<div class="device-row"><span class="device-logo ${d.vendor}">${d.vendor === 'zte' ? 'ZTE' : 'MT'}</span><div class="device-info"><strong>${esc(d.name)}</strong><small>${esc(d.management_ip)} · ${esc(d.model || d.device_type)}</small></div>${status(d.status)}</div>`).join('') : '<div class="empty-state">Belum ada device terdaftar.</div>'}</div></article><article class="content-card"><div class="card-header"><div><span class="eyebrow">RECENT ACTIVITY</span><h3>Syslog events</h3></div><button class="text-button" data-screen="syslog">View all ${svg('arrow')}</button></div><div class="event-list">${state.logs.length ? state.logs.slice(0, 5).map((l) => `<div class="event-row"><span class="event-severity severity-${l.severity || 'info'}"></span><div><strong>${esc(l.message)}</strong><small>${esc(l.source_ip || 'unknown')} · ${date(l.received_at)}</small></div></div>`).join('') : '<div class="empty-state">Belum ada syslog event.</div>'}</div></article></section>`;
    document.querySelector('#overview-refresh').onclick = async () => { await loadData(); toast('Data berhasil diperbarui.'); };
    document.querySelectorAll('.text-button').forEach((button) => button.onclick = () => { state.screen = button.dataset.screen; renderApp(); });
}

function renderDevices() {
    document.querySelector('#screen-content').innerHTML = `<div class="page-toolbar"><p class="muted">Kelola koneksi dan status perangkat network kamu.</p><button class="primary-button" id="add-device">${svg('plus')} Add device</button></div><div class="filter-row"><div class="search-box">${svg('search')}<input id="device-search" placeholder="Search device name or IP..."></div><div class="filter-chip active">All <b>${state.devices.length}</b></div><div class="filter-chip">Online</div><div class="filter-chip">Offline</div></div><article class="content-card table-card"><div class="table-wrap"><table><thead><tr><th>Device</th><th>Type</th><th>Management IP</th><th>Status</th><th>Last seen</th><th></th></tr></thead><tbody>${state.devices.length ? state.devices.map((d) => `<tr><td><div class="table-device"><span class="device-logo ${d.vendor}">${d.vendor === 'zte' ? 'ZTE' : 'MT'}</span><span><strong>${esc(d.name)}</strong><small>${esc(d.model || '—')}</small></span></div></td><td>${esc(d.device_type || '—')}</td><td class="mono">${esc(d.management_ip)}</td><td>${status(d.status)}</td><td>${date(d.last_seen_at)}</td><td><button class="row-action" data-test-device="${d.id}">Test</button></td></tr>`).join('') : '<tr><td colspan="6" class="empty-state">Belum ada device terdaftar.</td></tr>'}</tbody></table></div></article>`;
    document.querySelector('#add-device').onclick = showDeviceModal;
    document.querySelector('#device-search').oninput = (event) => { const q = event.target.value.toLowerCase(); document.querySelectorAll('tbody tr').forEach((row) => { row.style.display = row.textContent.toLowerCase().includes(q) ? '' : 'none'; }); };
    document.querySelectorAll('[data-test-device]').forEach((button) => button.onclick = async () => { button.disabled = true; try { const result = await api(`/devices/${button.dataset.testDevice}/test-connection`, { method: 'POST' }); toast(result.data.message); } catch (error) { toast(error.message, 'error'); } button.disabled = false; });
}

function renderSyslog() {
    document.querySelector('#screen-content').innerHTML = `<div class="page-toolbar"><p class="muted">Real-time event stream dari perangkat network.</p><span class="live-indicator large"><i></i>Listening for events</span></div><div class="filter-row"><div class="search-box">${svg('search')}<input id="log-search" placeholder="Search messages..."></div><div class="filter-chip active">All severities</div><div class="filter-chip">Critical</div><div class="filter-chip">Warning</div></div><article class="content-card table-card"><div class="table-wrap"><table><thead><tr><th>Severity</th><th>Message</th><th>Source</th><th>Received</th></tr></thead><tbody>${state.logs.length ? state.logs.map((l) => `<tr><td><span class="severity-label severity-${l.severity || 'info'}">${esc(l.severity || 'info')}</span></td><td><strong>${esc(l.message)}</strong></td><td class="mono">${esc(l.source_ip || '—')}</td><td>${date(l.received_at)}</td></tr>`).join('') : '<tr><td colspan="4" class="empty-state">Belum ada event syslog.</td></tr>'}</tbody></table></div></article>`;
    document.querySelector('#log-search').oninput = (event) => { const q = event.target.value.toLowerCase(); document.querySelectorAll('tbody tr').forEach((row) => { row.style.display = row.textContent.toLowerCase().includes(q) ? '' : 'none'; }); };
}

function renderScreen() { if (state.screen === 'overview') renderOverview(); if (state.screen === 'devices') renderDevices(); if (state.screen === 'syslog') renderSyslog(); }
async function loadData() { try { const [summary, devices, logs, me] = await Promise.all([api('/dashboard/summary'), api('/devices?per_page=100'), api('/syslog-events?per_page=20'), api('/me')]); state.summary = summary.data; state.devices = devices.data || []; state.logs = logs.data || []; state.user = me.data; if (!document.querySelector('.login-page')) renderApp(); } catch (error) { if (error.message.toLowerCase().includes('unauthenticated')) { localStorage.removeItem(TOKEN); renderLogin(); } else toast(error.message, 'error'); } }
function showDeviceModal() { const modal = document.createElement('div'); modal.className = 'modal-backdrop'; modal.innerHTML = `<div class="modal"><button class="modal-close">×</button><span class="eyebrow">NEW DEVICE</span><h2>Add network device</h2><p class="muted">Tambahkan device untuk mulai polling metrics.</p><form id="device-form"><label>Device name<input name="name" placeholder="OLT Jakarta 01" required></label><div class="form-grid"><label>Vendor<select name="vendor"><option value="zte">ZTE</option><option value="mikrotik">MikroTik</option></select></label><label>Device type<select name="device_type"><option value="olt">OLT</option><option value="router">Router</option><option value="switch">Switch</option></select></label></div><div class="form-grid"><label>Model<input name="model" placeholder="C320"></label><label>Management IP<input name="management_ip" placeholder="192.168.1.10" required></label></div><div class="form-grid"><label>Protocol<select name="protocol"><option value="snmp_v2c">SNMP v2c</option><option value="routeros_api">RouterOS API</option></select></label><label>Port<input name="port" type="number" value="161" required></label></div><label>Community / username<input name="community" placeholder="public"></label><button class="primary-button full" type="submit">Save device ${svg('arrow')}</button><p class="form-error" id="device-error"></p></form></div>`; document.body.append(modal); modal.querySelector('.modal-close').onclick = () => modal.remove(); modal.onclick = (e) => { if (e.target === modal) modal.remove(); }; modal.querySelector('#device-form').onsubmit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { await api('/devices', { method: 'POST', body: JSON.stringify({ name: data.name, vendor: data.vendor, model: data.model || null, device_type: data.device_type, management_ip: data.management_ip, is_polling_enabled: true, credentials: { protocol: data.protocol, port: Number(data.port), community: data.community } }) }); modal.remove(); await loadData(); toast('Device berhasil ditambahkan.'); } catch (error) { modal.querySelector('#device-error').textContent = error.message; } }; }

if (localStorage.getItem(TOKEN)) { renderApp(); loadData(); } else renderLogin();
